package lt.jono.petamante_backend.entity.enums;

public enum RoleName {
    ADMIN, USER, MODERATOR,
    VET_CLINIC, VET_DOCTOR, VET_HOTEL, VET_DAYCARE, VET_GROOMING, VET_SHOP,
    TRAINER, WALKER, FUNERAL_SERVICES,
    BREEDER, SHELTER, ANIMAL_REHABILITATION, ANIMAL_TRANSPORT,
    ANIMAL_PHOTOGRAPHY, ANIMAL_INSURANCE, BEHAVIOR_SPECIALIST, NUTRITION_CONSULTANT
}
