package lt.jono.petamante_backend.entity.enums;

public enum ServiceType {
    EXAMINATION, GROOMING, TRAINING, BOARDING, DAYCARE, FUNERAL,
    BREEDING_CONSULTATION, ADOPTION, REHABILITATION, TRANSPORT,
    PHOTOGRAPHY, INSURANCE_CONSULTATION, BEHAVIOR_CONSULTATION,
    NUTRITION_CONSULTATION, OTHER
}
